services:
  musicplayerproject:
    image: musicplayerproject
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - RENDER=true # Adicionado para garantir consistência
