name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Faz deploy apenas quando houver push na branch "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Fly.io CLI
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH=$HOME/.fly/bin:$PATH

      # Autentica no Fly.io
      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token $FLY_API_TOKEN

      # Faz o deploy no Fly.io
      - name: Deploy to Fly.io
        run: flyctl deploy