app = "music-player-project"  # Nome do aplicativo no Fly.io
primary_region = "gig"        # Região principal para o deploy

[build]
# Configurações de build podem ser adicionadas aqui, se necessário.

[env]
  RENDER = "true"             # Variável de ambiente para desativar pygame no Fly.io

[http_service]
  internal_port = 8080        # Porta interna usada pelo Gunicorn
  force_https = true          # Redireciona todo o tráfego para HTTPS
  auto_stop_machines = "stop" # Para máquinas inativas automaticamente
  auto_start_machines = true  # Inicia máquinas automaticamente quando necessário
  min_machines_running = 0    # Nenhuma máquina precisa estar sempre ativa
  processes = ["app"]         # Define o grupo de processos como "app"

[[vm]]
  memory = "1gb"              # Memória alocada para a máquina virtual
  cpu_kind = "shared"         # Tipo de CPU (compartilhada)
  cpus = 1                    # Número de CPUs alocadas
